<?php
	include("../include/condb.php");
	echo "<table>";
	echo "<caption>NUEVO USUARIO</caption>";
	echo "<tr>";
	echo "<td rowspan='8'><img src='shared/thumbs/imgnewuser_first.png'></td>";
	echo "<td width='30%'><b>NOMBRE DE ACCESO:</b></td>";
	echo "<td colspan='3' width='13%'><input style='width:90%;' autocomplete='off' id='accessuser' placeholder='ACCESO'/></td>";
	echo "</td>";
	echo "</tr>";
	echo "<tr>";
	echo "<td><b>CONTRASEÑA:</b></td>";
	echo "<td colspan='3' width='13%'><input type='password' style='width:90%;' autocomplete='off' id='passuser' placeholder='CONTRASEÑA'/></td>";	
	echo "</tr>";
	echo "<tr>";
	echo "<td><b>REPETIR CONTRASEÑA:</b></td>";
	echo "<td colspan='3' width='13%'><input type='password' style='width:90%;' autocomplete='off' id='passuser2' placeholder='CONTRASEÑA'/></td>";	
	echo "</tr>";		
	echo "<tr>";
	echo "<td><b>NOMBRE COMPLETO:</b></td>";
	echo "<td colspan='3' width='13%'><input style='width:90%;' autocomplete='off' id='fullnameuser' placeholder='NOMBRE COMPLETO'/></td>";	
	echo "</tr>";
	echo "<tr>";
	echo "<td><b>PRIVILEGIOS:</b></td>";
	$result=mysqli_query($db,"SELECT * FROM ROLES");
	echo "<td width='30%'> <select id='cmbRol' style='width:92%;'>";
	echo "<option value='-1' selected> -- Escoja sus privilegios -- </option>";		
		while($row = mysqli_fetch_assoc($result)) {				
echo"<option id ='priv_".$row['IDROLES']."' value='".$row['NOMBREROL']."'> ".$row['NOMBREROL']."</option>";		
		}
	echo "</select></td>";
	echo "</tr>";	
	echo "<tr>";
	echo "<td><b>TELEFONO:</b></td>";
	echo "<td colspan='3' width='13%'><input style='width:90%;' autocomplete='off' id='teluser' placeholder='TELEFONO'/></td>";
	echo "</tr>";
	echo "<tr>";
	echo "<td><b>CORREO-E:</b></td>";
	echo "<td colspan='3' width='13%'><input type='email' required style='width:90%;' autocomplete='off' id='mailuser' placeholder='CORREO-E:'/></td>";
	echo "</tr>";
	echo "<tr>";
	echo "<td width='13%'><b>PREGUNTA:</b></td>";
	echo "<td colspan ='2' width='30%'> <select id='questionuser' style='width:90%;'>";
	echo "<option value='1'>¿Cual es la fecha de nacimiento de tu madre?</option>";
	echo "<option value='2'>¿Cual fue tu primer vehiculo?</option>";					
	echo "<option value='3'>¿Cual es tu cancion favorita?</option>";						
	echo "<option value='4'>¿Cual es el nombre de tu primera mascota?</option>";							
	echo "<option value='5'>¿Cual es tu equipo deportivo favorito?</option>";								
	echo "<option value='6'>¿Donde enterraste el tesoro pirata?</option>";									
	echo "</select></td>";
	echo "</tr>";
	echo "<tr>";
	echo "<td width='13%'><b>RESPUESTA:</b></td>";
	echo "<td colspan='3'><textarea id='responseuser' style='width:100%;' cols='20' rows='3'></textarea></td>";
	echo "</tr>";
		echo "<tr>";
		echo "<td colspan='4' id='newusermessage'></td>";
		echo "</tr>";	
	echo "</table>";
	echo "<table class='commands'>";	
		echo "<tr>";
		echo "<td width='46%'></td>";	
		echo "<td width='18%'><a class='commandbutton' id='menu1'  onclick='newUser(this)' >";
		echo "<img src='shared/thumbs/btsale_ok.png' align='left' style='padding-right:5px;'> Crear usuario</a></td>";
		echo "</tr>";	
	echo "</table>";	
	
	echo "<table>";
	echo "<caption>SISTEMA</caption>";
	echo "<tr>";
	echo "<td rowspan='8'><img src='shared/thumbs/imgsystem_first.png'></td>";
	echo "<td width='30%'><b>CONSECUTIVO CON IVA:</b></td>";	
	echo "<td><input id='autoin1'  type='number' required='true' placeholder='consecutivo'  autocomplete='off' '/><br/></td>";
	echo "</tr>";	
	echo "<tr>";
	echo "<td width='30%'><b>CONSECUTIVO SIN IVA:</b></td>";		
	echo "<td><input  id='autoin2'  type='number' required='true' placeholder='consecutivo'  autocomplete='off'/><br/></td>";
	echo "</tr>";
		echo "<tr>";
		echo "<td colspan='4' id='systemnewincrement'></td>";
		echo "</tr>";	
	echo "</table>";
	echo "<table class='commands'>";	
		echo "<tr>";
		echo "<td width='46%'></td>";	
		echo "<td width='18%'><a class='commandbutton' id='menu1'  onclick='changeCodes(this)' >";
		echo "<img src='shared/thumbs/btsale_ok.png' align='left' style='padding-right:5px;'> guardar cambios </a></td>";
		echo "</tr>";	
	echo "</table>";
	
?>