<?php
    echo "<!doctype html>";
    echo "<html lang='es'>";
    echo "<head>";
	echo "<meta charset='UTF-8' />";
	echo "<title>Sistema de Gestion Empresarial</title>";
	echo "<link rel='stylesheet' href='shared/style.css'/>";
	echo "<script src='manager/jquery.min.js'></script>";
	echo "<script src='manager/jquery.ui.shake.js'></script>";
	echo "<script src='manager/jlogin.index.js'></script>";
	echo "</head>";
	echo "<body>";
	echo "<div id='main'>";
	echo "<div id='container'>";
	echo "<div class='forms'>";
	echo "<ul class='tabs'>";
	echo "<li>";
	echo "<a href='#login' class='active'>Entrada</a>";
	echo "</li>";
	echo "<li>";
	echo "<a href='#reset'>Ayuda</a>";
	echo "</li>";
	echo "</ul>";
	echo "<div id='login' class='form-action show'>";
	//echo "<h2>";
//	echo "<b>SIGO</b><br/>";
	//echo "<b>Sistema Integrado para la Gestion Organizacional</b></h2>";
	echo "<p>Al acceder podras generar facturas de venta, revisar el estado del inventario, ver la lista de clientes, ver la lista de productos.</p>";
	echo "<div id='error'></div>";
	echo "<form id='loginform' action='' method='post'>";
	echo "<input type='text' name='username' type='text' required='' placeholder='Usuario'  autocomplete='off' id='username'/>";
	echo "<br/>";
	echo "<input type='password' name='password'  type='password' required='' placeholder='Contraseña'  autocomplete='off' id='password'/><br/>";
	echo "<br/>";
	echo "<input class='button' type='submit' class='button button-primary' value='Acceder' id='btnlogin'/>"; 
	echo "</form>";	
	echo "</div>";  
	echo "<!--/#login.form-action-->";
	echo "<div id='reset' class='form-action hide'>";
	echo "<h1>Ayuda</h1>";
	echo "<p>Para registrasrte y ser un nuevo usuario, un Usuario administrador que este activo puede generarte como nuevo usuario de la aplicacion</p>";
	echo "</div>";
	echo "<!--/#register.form-action-->";
	echo "</div>";
	echo "</div>";
	echo "</div>";
	echo "</body>";
	echo "</html>";
?>
